// Copyright 2023 Audite Marlow (@auditemarlow)
// SPDX-License-Identifier: GPL-3.0

#pragma once

#define IGNORE_MOD_TAP_INTERRUPT
#define TAPPING_FORCE_HOLD
#define TAPPING_TERM 240
#define RETRO_TAPPING

#define MOUSEKEY_DELAY 5
#define MOUSEKEY_INTERVAL 16
#define MOUSEKEY_MOVE_DELTA 1
#define MOUSEKEY_INITIAL_SPEED 1
#define MOUSEKEY_DECELERATED_SPEED 12
#define MOUSEKEY_MAX_SPEED 22
#define USB_SUSPEND_WAKEUP_DELAY 0
#define MOUSEKEY_WHEEL_INTERVAL 83

#define MOUSEKEY_WHEEL_INTERVAL 83

#define MOUSEKEY_WHEEL_MAX_SPEED 3
